sudo: required
services:
  - docker

before_install:
  - docker build -t image -f Dockerfile.dev .

script:
  - docker run -e CI=true image npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "productionWorkflow"
  env: "ProductionWorkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-608600996002"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
